copy cphrinte.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\ 
copy hhcsinergia2.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zBONI.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zCOBRANZAMES1_4.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zCOBRANZAMES2_4.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zCOBRANZAMES3_4.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zCOBRANZAMES4_4.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zcopyapf_Delta19.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zCopyEdosCta.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zcopysicf_Delta19.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zcp_1011.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zcp_catasil.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zcp_gruma1011.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zcp_gruma1011.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zcpacreedor.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zcpcatal.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zcpd19.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zcpD19Diario.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zCPDatamart.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zcpdoccont.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zCP-facturasfi.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zcphrcata.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zcpinvdiario.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zcpjerar.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zcpmovmaterial.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zcpSIM_EXISTENCIAS.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zDATSSC.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zDEPOSITOS.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zDIRACTIVO.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zDIRACTIVOCAMBIOS.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zdmfinanzas.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zdmsim_cunitarios.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zdmsim_ege.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zdmsim_empaque.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zdmsim_energeticos.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zdmsim_existencias.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zdmsim_factagre.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zdmsim_nejayote.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zdmsim_produccion.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zdmsim_subproductos.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zdmsimnew.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zhhc_calc.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zhhcprecios.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zHHCPRODISA.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zhhcsinergianew.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zhomcam3775.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zhrad.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zhrintpro.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zhrintxpro.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zLOMMRE.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zmastrigo.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zMEZYCOMP.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zpedidostrigo.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zPREHOMCAM.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zSAPVaricent.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zSICF.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zSICFcopyTxt1Delta19Molinera.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zSICFcopyTxt2Delta19.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zSICFcopyTxt3Delta19.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zSICFCOPYTXTDelta19.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zSICFcopyTxtDelta19Molinera.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zSICFcopyTxtDelta19MolineraSicfed.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zSIL_INVENTARIOS.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zSIM_FPRODISA.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zSIM_RM5.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zsimt_prh.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zsimt_rt7.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\
copy zsimt_rt8.cmd V:\usr\sap\MXP\SYS\exe\nuc\NTAMD64\ZcmdInput\